apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ax0c31sva-python 
  janus-idp.io/tekton: ax0c31sva-python
  backstage.io/kubernetes-id: ax0c31sva-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ax0c31sva-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  