apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ax0c31sva-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ax0c31sva-python 
  name: ax0c31sva-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ax0c31sva-python 
